// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: editions/editions.proto

package editions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum in editions syntax
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_INACTIVE    Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_INACTIVE",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_INACTIVE":    2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_editions_editions_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_editions_editions_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_editions_editions_proto_rawDescGZIP(), []int{0}
}

// Simple nested message for testing lazy fields
type NestedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedMessage) Reset() {
	*x = NestedMessage{}
	mi := &file_editions_editions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedMessage) ProtoMessage() {}

func (x *NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_editions_editions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedMessage.ProtoReflect.Descriptor instead.
func (*NestedMessage) Descriptor() ([]byte, []int) {
	return file_editions_editions_proto_rawDescGZIP(), []int{0}
}

func (x *NestedMessage) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *NestedMessage) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *NestedMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Message with lazy field (only works with opaque API)
type MessageWithLazyField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *int32                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name  *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Lazy field - parsed on first access
	Nested        *NestedMessage `protobuf:"bytes,3,opt,name=nested" json:"nested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithLazyField) Reset() {
	*x = MessageWithLazyField{}
	mi := &file_editions_editions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithLazyField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithLazyField) ProtoMessage() {}

func (x *MessageWithLazyField) ProtoReflect() protoreflect.Message {
	mi := &file_editions_editions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithLazyField.ProtoReflect.Descriptor instead.
func (*MessageWithLazyField) Descriptor() ([]byte, []int) {
	return file_editions_editions_proto_rawDescGZIP(), []int{1}
}

func (x *MessageWithLazyField) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *MessageWithLazyField) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *MessageWithLazyField) GetNested() *NestedMessage {
	if x != nil {
		return x.Nested
	}
	return nil
}

// Regular message without lazy fields (should generate vtprotobuf methods)
type RegularMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Values        []int64                `protobuf:"varint,3,rep,packed,name=values" json:"values,omitempty"`
	Nested        *NestedMessage         `protobuf:"bytes,4,opt,name=nested" json:"nested,omitempty"`
	Metadata      map[string]int32       `protobuf:"bytes,5,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegularMessage) Reset() {
	*x = RegularMessage{}
	mi := &file_editions_editions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegularMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegularMessage) ProtoMessage() {}

func (x *RegularMessage) ProtoReflect() protoreflect.Message {
	mi := &file_editions_editions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegularMessage.ProtoReflect.Descriptor instead.
func (*RegularMessage) Descriptor() ([]byte, []int) {
	return file_editions_editions_proto_rawDescGZIP(), []int{2}
}

func (x *RegularMessage) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *RegularMessage) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RegularMessage) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *RegularMessage) GetNested() *NestedMessage {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *RegularMessage) GetMetadata() map[string]int32 {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Message demonstrating all scalar types in editions syntax
type ScalarTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoubleField   *float64               `protobuf:"fixed64,1,opt,name=double_field,json=doubleField" json:"double_field,omitempty"`
	FloatField    *float32               `protobuf:"fixed32,2,opt,name=float_field,json=floatField" json:"float_field,omitempty"`
	Int32Field    *int32                 `protobuf:"varint,3,opt,name=int32_field,json=int32Field" json:"int32_field,omitempty"`
	Int64Field    *int64                 `protobuf:"varint,4,opt,name=int64_field,json=int64Field" json:"int64_field,omitempty"`
	Uint32Field   *uint32                `protobuf:"varint,5,opt,name=uint32_field,json=uint32Field" json:"uint32_field,omitempty"`
	Uint64Field   *uint64                `protobuf:"varint,6,opt,name=uint64_field,json=uint64Field" json:"uint64_field,omitempty"`
	Sint32Field   *int32                 `protobuf:"zigzag32,7,opt,name=sint32_field,json=sint32Field" json:"sint32_field,omitempty"`
	Sint64Field   *int64                 `protobuf:"zigzag64,8,opt,name=sint64_field,json=sint64Field" json:"sint64_field,omitempty"`
	Fixed32Field  *uint32                `protobuf:"fixed32,9,opt,name=fixed32_field,json=fixed32Field" json:"fixed32_field,omitempty"`
	Fixed64Field  *uint64                `protobuf:"fixed64,10,opt,name=fixed64_field,json=fixed64Field" json:"fixed64_field,omitempty"`
	Sfixed32Field *int32                 `protobuf:"fixed32,11,opt,name=sfixed32_field,json=sfixed32Field" json:"sfixed32_field,omitempty"`
	Sfixed64Field *int64                 `protobuf:"fixed64,12,opt,name=sfixed64_field,json=sfixed64Field" json:"sfixed64_field,omitempty"`
	BoolField     *bool                  `protobuf:"varint,13,opt,name=bool_field,json=boolField" json:"bool_field,omitempty"`
	StringField   *string                `protobuf:"bytes,14,opt,name=string_field,json=stringField" json:"string_field,omitempty"`
	BytesField    []byte                 `protobuf:"bytes,15,opt,name=bytes_field,json=bytesField" json:"bytes_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalarTypes) Reset() {
	*x = ScalarTypes{}
	mi := &file_editions_editions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalarTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarTypes) ProtoMessage() {}

func (x *ScalarTypes) ProtoReflect() protoreflect.Message {
	mi := &file_editions_editions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarTypes.ProtoReflect.Descriptor instead.
func (*ScalarTypes) Descriptor() ([]byte, []int) {
	return file_editions_editions_proto_rawDescGZIP(), []int{3}
}

func (x *ScalarTypes) GetDoubleField() float64 {
	if x != nil && x.DoubleField != nil {
		return *x.DoubleField
	}
	return 0
}

func (x *ScalarTypes) GetFloatField() float32 {
	if x != nil && x.FloatField != nil {
		return *x.FloatField
	}
	return 0
}

func (x *ScalarTypes) GetInt32Field() int32 {
	if x != nil && x.Int32Field != nil {
		return *x.Int32Field
	}
	return 0
}

func (x *ScalarTypes) GetInt64Field() int64 {
	if x != nil && x.Int64Field != nil {
		return *x.Int64Field
	}
	return 0
}

func (x *ScalarTypes) GetUint32Field() uint32 {
	if x != nil && x.Uint32Field != nil {
		return *x.Uint32Field
	}
	return 0
}

func (x *ScalarTypes) GetUint64Field() uint64 {
	if x != nil && x.Uint64Field != nil {
		return *x.Uint64Field
	}
	return 0
}

func (x *ScalarTypes) GetSint32Field() int32 {
	if x != nil && x.Sint32Field != nil {
		return *x.Sint32Field
	}
	return 0
}

func (x *ScalarTypes) GetSint64Field() int64 {
	if x != nil && x.Sint64Field != nil {
		return *x.Sint64Field
	}
	return 0
}

func (x *ScalarTypes) GetFixed32Field() uint32 {
	if x != nil && x.Fixed32Field != nil {
		return *x.Fixed32Field
	}
	return 0
}

func (x *ScalarTypes) GetFixed64Field() uint64 {
	if x != nil && x.Fixed64Field != nil {
		return *x.Fixed64Field
	}
	return 0
}

func (x *ScalarTypes) GetSfixed32Field() int32 {
	if x != nil && x.Sfixed32Field != nil {
		return *x.Sfixed32Field
	}
	return 0
}

func (x *ScalarTypes) GetSfixed64Field() int64 {
	if x != nil && x.Sfixed64Field != nil {
		return *x.Sfixed64Field
	}
	return 0
}

func (x *ScalarTypes) GetBoolField() bool {
	if x != nil && x.BoolField != nil {
		return *x.BoolField
	}
	return false
}

func (x *ScalarTypes) GetStringField() string {
	if x != nil && x.StringField != nil {
		return *x.StringField
	}
	return ""
}

func (x *ScalarTypes) GetBytesField() []byte {
	if x != nil {
		return x.BytesField
	}
	return nil
}

// Message with enum
type MessageWithEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Status        *Status                `protobuf:"varint,2,opt,name=status,enum=Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithEnum) Reset() {
	*x = MessageWithEnum{}
	mi := &file_editions_editions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithEnum) ProtoMessage() {}

func (x *MessageWithEnum) ProtoReflect() protoreflect.Message {
	mi := &file_editions_editions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithEnum.ProtoReflect.Descriptor instead.
func (*MessageWithEnum) Descriptor() ([]byte, []int) {
	return file_editions_editions_proto_rawDescGZIP(), []int{4}
}

func (x *MessageWithEnum) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *MessageWithEnum) GetStatus() Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

// Message with oneof
type MessageWithOneof struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *int32                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// Types that are valid to be assigned to Choice:
	//
	//	*MessageWithOneof_StringChoice
	//	*MessageWithOneof_IntChoice
	//	*MessageWithOneof_MessageChoice
	Choice        isMessageWithOneof_Choice `protobuf_oneof:"choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithOneof) Reset() {
	*x = MessageWithOneof{}
	mi := &file_editions_editions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithOneof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithOneof) ProtoMessage() {}

func (x *MessageWithOneof) ProtoReflect() protoreflect.Message {
	mi := &file_editions_editions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithOneof.ProtoReflect.Descriptor instead.
func (*MessageWithOneof) Descriptor() ([]byte, []int) {
	return file_editions_editions_proto_rawDescGZIP(), []int{5}
}

func (x *MessageWithOneof) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *MessageWithOneof) GetChoice() isMessageWithOneof_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *MessageWithOneof) GetStringChoice() string {
	if x != nil {
		if x, ok := x.Choice.(*MessageWithOneof_StringChoice); ok {
			return x.StringChoice
		}
	}
	return ""
}

func (x *MessageWithOneof) GetIntChoice() int32 {
	if x != nil {
		if x, ok := x.Choice.(*MessageWithOneof_IntChoice); ok {
			return x.IntChoice
		}
	}
	return 0
}

func (x *MessageWithOneof) GetMessageChoice() *NestedMessage {
	if x != nil {
		if x, ok := x.Choice.(*MessageWithOneof_MessageChoice); ok {
			return x.MessageChoice
		}
	}
	return nil
}

type isMessageWithOneof_Choice interface {
	isMessageWithOneof_Choice()
}

type MessageWithOneof_StringChoice struct {
	StringChoice string `protobuf:"bytes,2,opt,name=string_choice,json=stringChoice,oneof"`
}

type MessageWithOneof_IntChoice struct {
	IntChoice int32 `protobuf:"varint,3,opt,name=int_choice,json=intChoice,oneof"`
}

type MessageWithOneof_MessageChoice struct {
	MessageChoice *NestedMessage `protobuf:"bytes,4,opt,name=message_choice,json=messageChoice,oneof"`
}

func (*MessageWithOneof_StringChoice) isMessageWithOneof_Choice() {}

func (*MessageWithOneof_IntChoice) isMessageWithOneof_Choice() {}

func (*MessageWithOneof_MessageChoice) isMessageWithOneof_Choice() {}

// Message with explicit IMPLICIT field presence (default behavior in edition 2023)
// These fields should be non-pointer types in Go
type ImplicitFieldPresence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyCode  string                 `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode" json:"currency_code,omitempty"`
	Units         int64                  `protobuf:"varint,2,opt,name=units" json:"units,omitempty"`
	Scale         int32                  `protobuf:"varint,3,opt,name=scale" json:"scale,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive" json:"is_active,omitempty"`
	Rate          float32                `protobuf:"fixed32,5,opt,name=rate" json:"rate,omitempty"`
	Amount        float64                `protobuf:"fixed64,6,opt,name=amount" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImplicitFieldPresence) Reset() {
	*x = ImplicitFieldPresence{}
	mi := &file_editions_editions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImplicitFieldPresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplicitFieldPresence) ProtoMessage() {}

func (x *ImplicitFieldPresence) ProtoReflect() protoreflect.Message {
	mi := &file_editions_editions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplicitFieldPresence.ProtoReflect.Descriptor instead.
func (*ImplicitFieldPresence) Descriptor() ([]byte, []int) {
	return file_editions_editions_proto_rawDescGZIP(), []int{6}
}

func (x *ImplicitFieldPresence) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *ImplicitFieldPresence) GetUnits() int64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *ImplicitFieldPresence) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *ImplicitFieldPresence) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ImplicitFieldPresence) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ImplicitFieldPresence) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Message with EXPLICIT field presence for comparison
// These fields should be pointer types in Go
type ExplicitFieldPresence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyCode  *string                `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode" json:"currency_code,omitempty"`
	Units         *int64                 `protobuf:"varint,2,opt,name=units" json:"units,omitempty"`
	Scale         *int32                 `protobuf:"varint,3,opt,name=scale" json:"scale,omitempty"`
	IsActive      *bool                  `protobuf:"varint,4,opt,name=is_active,json=isActive" json:"is_active,omitempty"`
	Rate          *float32               `protobuf:"fixed32,5,opt,name=rate" json:"rate,omitempty"`
	Amount        *float64               `protobuf:"fixed64,6,opt,name=amount" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplicitFieldPresence) Reset() {
	*x = ExplicitFieldPresence{}
	mi := &file_editions_editions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplicitFieldPresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplicitFieldPresence) ProtoMessage() {}

func (x *ExplicitFieldPresence) ProtoReflect() protoreflect.Message {
	mi := &file_editions_editions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplicitFieldPresence.ProtoReflect.Descriptor instead.
func (*ExplicitFieldPresence) Descriptor() ([]byte, []int) {
	return file_editions_editions_proto_rawDescGZIP(), []int{7}
}

func (x *ExplicitFieldPresence) GetCurrencyCode() string {
	if x != nil && x.CurrencyCode != nil {
		return *x.CurrencyCode
	}
	return ""
}

func (x *ExplicitFieldPresence) GetUnits() int64 {
	if x != nil && x.Units != nil {
		return *x.Units
	}
	return 0
}

func (x *ExplicitFieldPresence) GetScale() int32 {
	if x != nil && x.Scale != nil {
		return *x.Scale
	}
	return 0
}

func (x *ExplicitFieldPresence) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *ExplicitFieldPresence) GetRate() float32 {
	if x != nil && x.Rate != nil {
		return *x.Rate
	}
	return 0
}

func (x *ExplicitFieldPresence) GetAmount() float64 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

var File_editions_editions_proto protoreflect.FileDescriptor

const file_editions_editions_proto_rawDesc = "" +
	"\n" +
	"\x17editions/editions.proto\"G\n" +
	"\rNestedMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"f\n" +
	"\x14MessageWithLazyField\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x06nested\x18\x03 \x01(\v2\x0e.NestedMessageB\x02(\x01R\x06nested\"\xec\x01\n" +
	"\x0eRegularMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06values\x18\x03 \x03(\x03R\x06values\x12&\n" +
	"\x06nested\x18\x04 \x01(\v2\x0e.NestedMessageR\x06nested\x129\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1d.RegularMessage.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x9a\x04\n" +
	"\vScalarTypes\x12!\n" +
	"\fdouble_field\x18\x01 \x01(\x01R\vdoubleField\x12\x1f\n" +
	"\vfloat_field\x18\x02 \x01(\x02R\n" +
	"floatField\x12\x1f\n" +
	"\vint32_field\x18\x03 \x01(\x05R\n" +
	"int32Field\x12\x1f\n" +
	"\vint64_field\x18\x04 \x01(\x03R\n" +
	"int64Field\x12!\n" +
	"\fuint32_field\x18\x05 \x01(\rR\vuint32Field\x12!\n" +
	"\fuint64_field\x18\x06 \x01(\x04R\vuint64Field\x12!\n" +
	"\fsint32_field\x18\a \x01(\x11R\vsint32Field\x12!\n" +
	"\fsint64_field\x18\b \x01(\x12R\vsint64Field\x12#\n" +
	"\rfixed32_field\x18\t \x01(\aR\ffixed32Field\x12#\n" +
	"\rfixed64_field\x18\n" +
	" \x01(\x06R\ffixed64Field\x12%\n" +
	"\x0esfixed32_field\x18\v \x01(\x0fR\rsfixed32Field\x12%\n" +
	"\x0esfixed64_field\x18\f \x01(\x10R\rsfixed64Field\x12\x1d\n" +
	"\n" +
	"bool_field\x18\r \x01(\bR\tboolField\x12!\n" +
	"\fstring_field\x18\x0e \x01(\tR\vstringField\x12\x1f\n" +
	"\vbytes_field\x18\x0f \x01(\fR\n" +
	"bytesField\"B\n" +
	"\x0fMessageWithEnum\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\x06status\x18\x02 \x01(\x0e2\a.StatusR\x06status\"\xad\x01\n" +
	"\x10MessageWithOneof\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12%\n" +
	"\rstring_choice\x18\x02 \x01(\tH\x00R\fstringChoice\x12\x1f\n" +
	"\n" +
	"int_choice\x18\x03 \x01(\x05H\x00R\tintChoice\x127\n" +
	"\x0emessage_choice\x18\x04 \x01(\v2\x0e.NestedMessageH\x00R\rmessageChoiceB\b\n" +
	"\x06choice\"\xdb\x01\n" +
	"\x15ImplicitFieldPresence\x12*\n" +
	"\rcurrency_code\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x02R\fcurrencyCode\x12\x1b\n" +
	"\x05units\x18\x02 \x01(\x03B\x05\xaa\x01\x02\b\x02R\x05units\x12\x1b\n" +
	"\x05scale\x18\x03 \x01(\x05B\x05\xaa\x01\x02\b\x02R\x05scale\x12\"\n" +
	"\tis_active\x18\x04 \x01(\bB\x05\xaa\x01\x02\b\x02R\bisActive\x12\x19\n" +
	"\x04rate\x18\x05 \x01(\x02B\x05\xaa\x01\x02\b\x02R\x04rate\x12\x1d\n" +
	"\x06amount\x18\x06 \x01(\x01B\x05\xaa\x01\x02\b\x02R\x06amount\"\xdb\x01\n" +
	"\x15ExplicitFieldPresence\x12*\n" +
	"\rcurrency_code\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x01R\fcurrencyCode\x12\x1b\n" +
	"\x05units\x18\x02 \x01(\x03B\x05\xaa\x01\x02\b\x01R\x05units\x12\x1b\n" +
	"\x05scale\x18\x03 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x05scale\x12\"\n" +
	"\tis_active\x18\x04 \x01(\bB\x05\xaa\x01\x02\b\x01R\bisActive\x12\x19\n" +
	"\x04rate\x18\x05 \x01(\x02B\x05\xaa\x01\x02\b\x01R\x04rate\x12\x1d\n" +
	"\x06amount\x18\x06 \x01(\x01B\x05\xaa\x01\x02\b\x01R\x06amount*H\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_INACTIVE\x10\x02B\x14Z\x12testproto/editionsb\beditionsp\xe8\a"

var (
	file_editions_editions_proto_rawDescOnce sync.Once
	file_editions_editions_proto_rawDescData []byte
)

func file_editions_editions_proto_rawDescGZIP() []byte {
	file_editions_editions_proto_rawDescOnce.Do(func() {
		file_editions_editions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_editions_editions_proto_rawDesc), len(file_editions_editions_proto_rawDesc)))
	})
	return file_editions_editions_proto_rawDescData
}

var file_editions_editions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_editions_editions_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_editions_editions_proto_goTypes = []any{
	(Status)(0),                   // 0: Status
	(*NestedMessage)(nil),         // 1: NestedMessage
	(*MessageWithLazyField)(nil),  // 2: MessageWithLazyField
	(*RegularMessage)(nil),        // 3: RegularMessage
	(*ScalarTypes)(nil),           // 4: ScalarTypes
	(*MessageWithEnum)(nil),       // 5: MessageWithEnum
	(*MessageWithOneof)(nil),      // 6: MessageWithOneof
	(*ImplicitFieldPresence)(nil), // 7: ImplicitFieldPresence
	(*ExplicitFieldPresence)(nil), // 8: ExplicitFieldPresence
	nil,                           // 9: RegularMessage.MetadataEntry
}
var file_editions_editions_proto_depIdxs = []int32{
	1, // 0: MessageWithLazyField.nested:type_name -> NestedMessage
	1, // 1: RegularMessage.nested:type_name -> NestedMessage
	9, // 2: RegularMessage.metadata:type_name -> RegularMessage.MetadataEntry
	0, // 3: MessageWithEnum.status:type_name -> Status
	1, // 4: MessageWithOneof.message_choice:type_name -> NestedMessage
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_editions_editions_proto_init() }
func file_editions_editions_proto_init() {
	if File_editions_editions_proto != nil {
		return
	}
	file_editions_editions_proto_msgTypes[5].OneofWrappers = []any{
		(*MessageWithOneof_StringChoice)(nil),
		(*MessageWithOneof_IntChoice)(nil),
		(*MessageWithOneof_MessageChoice)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_editions_editions_proto_rawDesc), len(file_editions_editions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_editions_editions_proto_goTypes,
		DependencyIndexes: file_editions_editions_proto_depIdxs,
		EnumInfos:         file_editions_editions_proto_enumTypes,
		MessageInfos:      file_editions_editions_proto_msgTypes,
	}.Build()
	File_editions_editions_proto = out.File
	file_editions_editions_proto_goTypes = nil
	file_editions_editions_proto_depIdxs = nil
}
